[package]
name = "macigè"
version = "1.0.0"
edition = "2021"

[dependencies]
yew = { git = "https://github.com/yewstack/yew.git", features = ["csr"] }
yew-hooks = { git = "https://github.com/jetli/yew-hooks" }
gloo = "0.8.0"
gloo-utils = { version = "0.1.5", features = ["serde"] }
askama = "0.11"
wasm-bindgen = "0.2.83"
strum = "0.24.1"
strum_macros = "0.24.1"
serde = "1.0.147"
serde_derive = "1.0.147"
log = "0.4.6"
web-sys = { version = "0.3.60", features = ["HtmlSelectElement", "HtmlElement"]}
wasm-logger = "0.2.0"

[profile.release]
panic = 'abort'
# optimization over all codebase (better optim, slower build)
codegen-units = 1
# optimization for size (more aggressive)
opt-level = 'z'
# optimization for size
# opt-level = 's'
# link time optimization using using whole-program analysis
lto = true